### PR TITLE
http3: use a log/slog Logger for logging

### LINKED ISSUE #3548: http3: use the http.Server.ErrorLog if set
In a previous version, `v0.28` if I'm not mistaken, there was a possibility to set `http3.Server.Server.ErrorLog = log.New (...)`.  However now as the `http3.Server.Server` fields have been merged into `http3.Server`, the `ErrorLog` is missing.

There seems to be a private `logger util.Logger` field that can't be overriden, so perhaps making that public?

### LINKED ISSUE #4366: http3 server silently panics
With a std HTTP server I would expect the following code to print some indication that the goroutine handling the request panicked:

```go
package main

import (
        "flag"
        "net/http"
        "log"

	"github.com/quic-go/quic-go/http3"
)

func main() {
        cert := flag.String("crt", "", "Cert")
        key := flag.String("key", "", "Key")
        flag.Parse()

        http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
                panic("Hi there")
        })

        log.Fatal(http3.ListenAndServeQUIC(":443", *cert, *key, nil))
}
```

But http3 appears to just silently eat the panic. If this behavior is intentional, is there a way to surface panics so I am aware they're happening?

### PR DESCRIPTION
**Pull request by marten-seemann**
Fixes #4366. Closes #3548.

### CODE REVIEW

File: http3/client.go [hunk 1]
```diff
@@ -74,14 +75,15 @@ func (c *SingleDestinationRoundTripper) Start() Connection {
...
 	c.decoder = qpack.NewDecoder(func(hf qpack.HeaderField) {})
-	c.hconn = newConnection(c.Connection, c.EnableDatagrams, c.UniStreamHijacker, protocol.PerspectiveClient, c.logger)
+	c.hconn = newConnection(c.Connection, c.EnableDatagrams, c.UniStreamHijacker, protocol.PerspectiveClient, c.Logger)
 	// send the SETTINGs frame, using 0-RTT data, if possible
 	go func() {
 		if err := c.setupConn(c.Connection); err != nil {
-			c.logger.Debugf("Setting up connection failed: %s", err)
+			if c.Logger != nil {
+				c.Logger.Debug("setting up connection failed", "error", err)
+			}
```
Comment (rfwatson) [inline http3/client.go:86]: Question: should we always fallback to `slog.Default()` if no logger is explicitly set?

**Review by rfwatson — APPROVED** [review]
Thanks for updating this :pray:

File: http3/client.go (hunk 1 above)
Comment (marten-seemann) [reply http3/client.go:86]: I'm not sure. I don't want to spam peoples' logs with debug messages, so I'm inclined to leave it as is far now. That said, I don't think we have a good / consistent logging philosophy at the moment, so I'd be happy to discuss and revise this decision in the future.
